### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by suzumakes** [rileyhilliard/reportcard#10]
XMLHttpRequest cannot load http://teamtreehouse.com/username.json. 

No 'Access-Control-Allow-Origin' header is present on the requested resource. 

Origin 'http://website.com' is therefore not allowed access.

Just a heads up for you, I'm looking into fixing it later today.

**Comment by rileyhilliard** [comment]
Hey @suzumakes,
I have verified that it looks like Treehouse has changed their API and removed the 'Access-Control-Allow-Origin headers, so the API call is failing now. This might require some communication with treehouse, to either return JSONP, or replace the correct headers in their API. From my communication with them in the past, they should be pretty open to helping out. Let me know if you make any headway, otherwise, I'll try and contact treehouse sometime this week

**Comment by suzumakes** [comment]
They've fixed it, I didn't even get the chance to ask them about it. Thanks @rileyhilliard
